# Generated by Django 4.2.2 on 2023-06-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_colaborador_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='aportador',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aportador',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
